console.log(document.getElementByName("id"))
console.log(document.getElementByName("nombre"))
console.log(document.getElementByName("precio"))
console.log(document.getElementByName("fechaDeLanzamiento"))
console.log(document.getElementByName("descripcion"))
console.log(document.getElementByName("descripcionSlider"))
console.log(document.getElementByName("generos"))
console.log(document.getElementByName("desarrollador"))
console.log(document.getElementByName("editor"))
console.log(document.getElementByName("franquicia"))


console.log(document.getElementByName("imgPathV"))
console.log(document.getElementByName("imgSliderPath"))
console.log(document.getElementByName("videoPath"))
console.log(document.getElementByName("productoDestacado"))
console.log(document.getElementByName("productoOferta"))
console.log(document.getElementByName("descuento"))
console.log(document.getElementByName("requisitosSistemaMinimos"))
console.log(document.getElementByName("dato"))
console.log(document.getElementByName("so"))
console.log(document.getElementByName("procesador"))
console.log(document.getElementByName("memoria"))
console.log(document.getElementByName("almacenamiento"))
console.log(document.getElementByName("graficos"))
console.log(document.getElementByName("tarjeta_sonido"))
console.log(document.getElementByName("requisitosSistemaRecomendados"))